### ISSUE TITLE
No writable property 'url' on class: io.kamax.mxisd.config.ListenerConfig

### ISSUE THREAD

**Issue by NullIsNot0** [kamax-matrix/mxisd#131]
After migrating from 1.2.2 to 1.3.0 e-mail notification configuration crashes mxisd docker container.

Configuration part:
```
...
matrix:
    domain: example.com
    listener:
        localpart: appservice-mxisd
        token:
            as: 9pBE4fo8qsFjOM0dELtpvTrA6BLYCndS8Nzqrv1laTqiW3oAXDHzxQ0otT3p1J1j
            hs: yNabQ67LO55IedMod2cQYwaEUfWtpEsAKz4bNS2sQ8SCr8NyOX7y9rFv1kDvxFja
        url: http://matrix-synapse:8090
...
```

Error I get:
```
No writable property 'url' on class: io.kamax.mxisd.config.ListenerConfig
in 'reader', line 37, column 14:
url: http://matrix-synapse:8090
```
This configuration worked well in 1.2.2.
