### ISSUE TITLE
LDAP/AD name displayname problem

### ISSUE THREAD

**Issue by tgurr** [kamax-matrix/mxisd#135]
I've followed https://github.com/kamax-matrix/mxisd/blob/master/docs/stores/ldap.md

in mxisd.yaml I have:

```
ldap:
  enabled: true
  connection:
    host: 'xxx'
    port: 389
    bindDn: 'CN=xxx,OU=xxx,DC=xxx,DC=xxx'
    bindPassword: 'xxx'
    baseDNs:
      - 'OU=xxx,DC=xxx,DC=xxx'
  attribute:
    name: 'cn'
```

and in homserver.yaml

```
password_providers:
  - module: "rest_auth_provider.RestAuthProvider"
    config:
      endpoint: "http://localhost:8090"
      policy:
        registration:
          profile:
            name: true
        login:
          profile:
            name: true
```

When loggin in with riot-web I can see the name correctly changing on every login in the left corner whether I set the `name:` attribute in myisd.yaml to either `'cn'`:

![riot_cn](https://user-images.githubusercontent.com/414984/53167907-9f66ca80-35d9-11e9-975c-290280391d25.png)

or `'displayName'`:

![riot_displayname](https://user-images.githubusercontent.com/414984/53167914-a261bb00-35d9-11e9-9e0e-7a94c7f65b89.png)

so generally it appear to work so far.

However my question is in the riot-web/matrix profile the "Display Name" is not applied and/or changing accordingly, so in the rooms I'm still appearing with the `matrixid:server.xxx ` instead of the correct `name:` transferred by mxisd via LDAP:

![riot_web](https://user-images.githubusercontent.com/414984/53168185-624f0800-35da-11e9-91dd-1ab121a133e1.png)

Is there anything I'm missing out?
