### ISSUE TITLE
LDAP users from AD & case sensitivity

### ISSUE THREAD

**Issue by tgurr** [kamax-matrix/mxisd#151]
We've recently discovered a problem. When searching for users e.g. to invite them to a room or a direct chat the results are displayed in upper case, e.g. `@TESTUSER123:domain.local` and an invite to any room or direct chat will fail/not reach the matrix user.

If the user previously logged in to matrix so a matrix id is already present the search result displays both, the one from AD `@TESTUSER123:domain.local` and the matrix one `@testuser123:domain.local` so users wonder why there are two results and the more urgent problem they often invite the wrong one.

Is there any option for mxisd to force the output/return of the user to be lowercase?

**Comment by maxidorius** [comment]
Given that mxisd uses the same attribute for all User Id computations, could you clarify how the users are created on the Matrix side? It doesn't make sense that in one case it would be lower case but in the other it would be upper case.

**Comment by tgurr** [comment]
I guess they're created automatically when logging in via a client like Riot the first time, at least I don't create any users manually.

Just having setup mxisd

```
ldap:
  enabled: true
  connection:
    host: 'dc.domain.local'
    port: 389
    bindDn: 'CN=matrixldapuser,OU=services,DC=domain,DC=local'
    bindPassword: 'xxx'
    baseDNs:
      - 'OU=users,DC=domain,DC=local'
```

and synapse like:

```
password_providers:
  - module: "rest_auth_provider.RestAuthProvider"
    config:
      endpoint: "http://localhost:8090"
      policy:
        registration:
          profile:
            name: true
        login:
          profile:
            name: true
```
Please let me know if I miss any useful information. My guess is that in matrix everything is lowercase, but the LDAP search from the identity server (mxisd) returns the sAMAccountName 1:1 like it is stored in AD instead of forcing the output to be lowercase. Logging in to Riot for example does only work when providing the login in lowercase and the matrix user also gets created fine in lowercase, it's just the search results comming from LDAP/AD that seem to be off.
