### ISSUE TITLE
LDAP search ignores attribute mapping in config

### ISSUE THREAD

**Issue by Radarum** [kamax-matrix/mxisd#152]
mxisd uses sAMAccountName as uid in search ignoring config, as seen in LDAP server log

```
[05/Apr/2019:09:55:20.302007481 +0300] conn=1185 fd=64 slot=64 connection from 10._._._ to 10._._._
[05/Apr/2019:09:55:20.344301938 +0300] conn=1185 op=0 BIND dn="" method=128 version=3
[05/Apr/2019:09:55:20.344404996 +0300] conn=1185 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0000225881 dn=""
[05/Apr/2019:09:55:20.365055306 +0300] conn=1185 op=1 SRCH base="ou=redacted,dc=_redacted_,dc=_redacted_" scope=2 filter="(samaccountname=_redacted_)" attrs="othertelephone otherhomephone telephoneNumber samaccountname mail displayName mailprimaryaddress homePhone othermailbox mobile othermobile"
[05/Apr/2019:09:55:20.386157479 +0300] conn=1185 op=1 RESULT err=0 tag=101 nentries=0 etime=0.0021227238 notes=U
[05/Apr/2019:09:55:20.388100913 +0300] conn=1185 op=-1 fd=64 closed - B1
```

LDAP server is ns-slapd version 389-Directory/1.3.8.4 B2019.073.1017
mxisd version 1.3.1

```
ldap:
  enabled: true
  connection:
    host: '_redacted_'
    tls: false
    port: 389
    # bindDn: ''
    # bindPassword: ''
    baseDNs:
      - 'ou=_redacted_,dc=_redacted_,dc=_redacted_'
    attribute:
      uid:
        type: 'uid'
        value: 'uid'
      password: 'userPassword'
      name: 'displayName'
      threepid:
        email: 'mail'
```

[Used this doc](https://github.com/kamax-matrix/mxisd/blob/master/docs/stores/ldap.md)
