### ISSUE TITLE
invite 

### ISSUE THREAD

**Issue by Unsourire** [kamax-matrix/mxisd#161]
hello,
i put the configuraion as described on the directory.md documentation.

i put the proxypass,
 in insert :
```
dns:
  overwrite:
    homeserver:
      client:
        - name: 'example.org'
          value: 'http://localhost:8008'
```

and i put the synapse indenties store.

but i got the error :
`An internal server error occured. If this error persists, please contact support with reference #1555514297474`

Do you have any suggestion

**Comment by Unsourire** [comment]
erro message

[XNIO-1 task-2] INFO io.kamax.mxisd.directory.DirectoryManager - Performing search for 'fdf'
[XNIO-1 task-2] INFO io.kamax.mxisd.directory.DirectoryManager - Original request URL: http://example.org/_matrix/client/r0/user_directory/search
[XNIO-1 task-2] ERROR io.kamax.mxisd.http.undertow.handler.SaneHandler - Reference #1555516611704 - No DNS client override for example.org
[XNIO-1 task-2] INFO io.kamax.mxisd.http.undertow.handler.BasicHttpHandler - Request POST http://example.org/_matrix/client/r0/user_directory/search - Error M_UNKNOWN: An internal server error occured. If this error persists, please contact support with reference #1555516611704

**Comment by maxidorius** [comment]
You are most likely missing the directive in your reverse proxy configuration to preserve the `Host` header.

**Comment by Unsourire** [comment]
I checked and everything is well configured and now i got the following error 👎 [XNIO-1 task-2] 
[XNIO-1 task-2] INFO io.kamax.mxisd.directory.DirectoryManager - Performing search for 'jl'
[XNIO-1 task-2] INFO io.kamax.mxisd.directory.DirectoryManager - Original request URL: http://example.org/_matrix/client/r0/user_directory/search
[XNIO-1 task-2] INFO io.kamax.mxisd.directory.DirectoryManager - Querying HS at https://localhost:8049/_matrix/client/r0/user_directory/search
ERROR io.kamax.mxisd.http.undertow.handler.SaneHandler - Transaction #1555522350994 - Unable to query the HS: I/O error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[XNIO-1 task-2] INFO io.kamax.mxisd.http.undertow.handler.BasicHttpHandler - Request POST http://smsnt.eu/_matrix/client/r0/user_directory/search - Error M_UNKNOWN: An internal server error occured. If this error persists, please contact support with reference #1555522350994

**Comment by Unsourire** [comment]
I solve the first problem.
it was the https protocol , i changed it to http and the good port ansd it's working.
but i have a lot of error with The 3pids mapping.
because there is no link (on matrix) with the mail adresse and the username even in putting the federation with the dns overwire. 
for exemple i have the following message 
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.invitation.InvitationManager - Searching for mapping created after invite @toto:example.org:!rokwOLCdRVMjUdCaYz:smsnt.eu:email:toto123@hotmail.com was created
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - Host Internal allowed for recursion: true
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.lookup.provider.DnsLookupProvider - Performing DNS lookup for toto123@hotmail.com
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.lookup.provider.DnsLookupProvider - Domain name for toto123@hotmail.com: hotmail.com
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.matrix.IdentityServerUtils - hotmail.com is not an URL, using as-is
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.matrix.IdentityServerUtils - Discovering Identity Server for hotmail.com
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.matrix.IdentityServerUtils - Performing SRV lookup
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.matrix.IdentityServerUtils - Lookup name: _matrix-identity._tcp.hotmail.com
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.matrix.IdentityServerUtils - No SRV record for _matrix-identity._tcp.hotmail.com
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - No 3PID mapping found
[ForkJoinPool.commonPool-worker-1] INFO io.kamax.mxisd.invitation.InvitationManager - No mapping for pending invite @toto:smsnt.eu:!rokwOLCdRVMjUdCaYz:smsnt.eu:email:toto123@hotmail.com

Thank you for your help

**Comment by maxidorius** [comment]
Those are not errors, they are regular and expected attempts to resolve a pending invite over the federation. If you would like to tune those (timing, usage of federation) see the relevant [documentation](https://github.com/kamax-matrix/mxisd/blob/master/docs/features/identity.md#resolution)

**Comment by Unsourire** [comment]
Thank you for the answer.
But i have a probleme when i vinvitesomeone to a room.
I can send the invitation but even when he creates an account i can't receive the invitation (on riot for example) to join the group. i can only add user by the matrix account name.
I have added on the matrix confiugration of the 3PID email
and on mxisd :
```
matrix:
  domain: 'exemple.org'
key:
  path: '/home/clients......9/mxisd/sign.key'
storage:
  provider:
    sqlite:
      database: '/home/.................59/mxisd/mxisd.db'
synapseSql:
  enabled: true
synapseSql:
  type: sqlite
synapseSql:
  connection: /home/clients/...........9/.synapse/homeserver.db
lookup:
  recursive:
    enabled: false
invite:
  resolution:
    recursive: false
invite:
  expiration:
    enabled: true
  session:
  policy:
    validation:
      enabled: true
      forLocal:
        enabled: true
        toLocal: true
        toRemote:
          enabled: false
      forRemote:
        enabled: true
        toLocal: true
        toRemote:
          enabled: false 
notification:
  handler:
    email: 'raw'
threepid:
  medium:
    email:
      identity:
        # The e-mail to send as.
        from: "noreply@chat.eu"
        name: " Chat"

      connectors:
        smtp:
          host: "localhost"
          port: 25
      generators:
        template:
          invite: '/ho..........invite_template.eml'        
dns:
  overwrite:
    homeserver:
      client:
        - name: 'example.org'
          value: 'http://localhost:8009'   
``` 
Do i miss to add something?
also we got a error withe 3PID when i have the following configuration i can't create account because a error of email 3PID :
```
session:
  policy:
    validation:
      enabled: true
session:
  policy:
    validation:
      forLocal:
        enabled: true
        toLocal: true
        toRemote:
          enabled: false

session:
  policy:
    validation:
      forRemote:
        enabled: true
        toLocal: true
        toRemote:
          enabled: false 
```
but with the following is working :
```
session:
  policy:
    validation:
      enabled: true
      forLocal:
        enabled: true
        toLocal: true
        toRemote:
          enabled: false
      forRemote:
        enabled: true
        toLocal: true
        toRemote:
          enabled: false 
```

**Comment by Unsourire** [comment]
hello,
we solve the solution by adding the following
```
dns:
  overwrite:
    homeserver:
      federation:
        - name: 'chat.eu'
          value: 'http://localhost:8009'       
      client:
        - name: 'chat.eu'
          value: 'http://localhost:8009'  

synapseSql:
  enabled: true
  type: sqlite
  connection: /home/clients/......................./.synapse/homeserver.db
```
but we have the following warning is it important?

```
[Thread-19] INFO io.kamax.mxisd.invitation.InvitationManager - Posting onBind event to http://localhost:8009/_matrix/federation/v1/3pid/onbind
[Thread-18] INFO io.kamax.mxisd.invitation.InvitationManager - Answer code: 500
[Thread-18] WARN io.kamax.mxisd.invitation.InvitationManager - Answer body: {"errcode":"M_UNKNOWN","error":"Internal server error"}
[Thread-19] INFO io.kamax.mxisd.invitation.InvitationManager - Answer code: 500
[Thread-19] WARN io.kamax.mxisd.invitation.InvitationManager - Answer body: {"errcode":"M_UNKNOWN","error":"Internal server error"}
```
