### ISSUE TITLE
Issue when searching a user on LDAP

### ISSUE THREAD

**Issue by mjattiot** [kamax-matrix/mxisd#165]
Hello everyone,

I am trying to setup the directory search feature in mxisd, using LDAP provider.
While searching for a user I have a correct match when mxisd is looking for the "Display name" but then mxisd is looking on 3PIDs and matches every entries !

Correct match on display name:
```
[XNIO-1 task-5] INFO io.kamax.mxisd.backend.ldap.LdapDirectoryProvider - Performing LDAP directory search on display name using 'mja'
[XNIO-1 task-5] INFO io.kamax.mxisd.backend.ldap.LdapDirectoryProvider - Found possible match, DN: uid=mjattiot,ou=Users,dc=opensense,dc=fr
[XNIO-1 task-5] INFO io.kamax.mxisd.backend.ldap.LdapDirectoryProvider - DN uid=mjattiot,ou=Users,dc=opensense,dc=fr is a valid match
[XNIO-1 task-5] INFO io.kamax.mxisd.directory.DirectoryManager - Display name: found 1 match(es) for 'mja'
```

Matching every entries on 3PIDs ...
```
[XNIO-1 task-5] INFO io.kamax.mxisd.backend.ldap.LdapDirectoryProvider - Performing LDAP directory search on 3PIDs using 'mja'
[XNIO-1 task-5] INFO io.kamax.mxisd.backend.ldap.LdapDirectoryProvider - Found possible match, DN: uid=mjattiot,ou=Users,dc=opensense,dc=fr
[XNIO-1 task-5] INFO io.kamax.mxisd.backend.ldap.LdapDirectoryProvider - DN uid=mjattiot,ou=Users,dc=opensense,dc=fr is a valid match
[XNIO-1 task-5] INFO io.kamax.mxisd.backend.ldap.LdapDirectoryProvider - Found possible match, DN: uid=hbaptiste,ou=Users,dc=opensense,dc=fr
[...]
[XNIO-1 task-5] INFO io.kamax.mxisd.directory.DirectoryManager - Threepid: found 10 match(es) for 'mja'
[XNIO-1 task-5] INFO io.kamax.mxisd.directory.DirectoryManager - Total matches: 10 - limited? false
```

I have setup a 3PID mapping on emails and the word 'mja' is only present on one email out of our 10 users. This is strange that everything matches. Any clues ?

My configuration is the following:
```
ldap:
  enabled: true
  connection:
    [...]
    baseDNs:
      - 'ou=Users,dc=opensense,dc=fr'
  attribute:
    uid:
      type: 'uid'
      value: 'uid'
    name: 'cn'
    threepid:
      email:
        - 'mail'

session:
  policy:
    validation:
      enabled: false

dns:
  overwrite:
    homeserver:
      client:
        - name: 'my_homeserver'
          value: 'http://matrix-server:8008'
```
