### ISSUE TITLE
Invitation notifications to e-mail do not work after upgrading to 1.4.2

### ISSUE THREAD

**Issue by NullIsNot0** [kamax-matrix/mxisd#171]
I'm using project [spantaleev/matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) and after upgrading Docker image from `kamax/mxisd:1.3.1-1-gc636500` to `kamax/mxisd:1.4.2` and changing mxisd's config from 
```yaml
matrix:
    listener:
      url:  "{{ matrix_mxisd_dns_overwrite_homeserver_client_value }}"
      localpart: 'appservice-mxisd'
      token:
        hs: "{{ matrix_synapse_hs_token }}"
        as: "{{ matrix_synapse_as_token }}"
```
to
```yaml
appsvc:
    enabled: true
    registration:
      synapse:
        id: 'appservice-mxisd'
    endpoint:
      toHS:
        url: '{{ matrix_mxisd_dns_overwrite_homeserver_client_value }}'
        token: '{{ matrix_synapse_hs_token }}'
      toAS:
        url: 'http://{{ matrix_nginx_proxy_proxy_matrix_identity_api_addr_with_container }}'
        token: '{{ matrix_synapse_as_token }}'
synapseSql:
    enabled: true ## Do not use this line if Synapse is used as an Identity Store
    type: 'postgresql'
    connection: '//{{ matrix_postgres_connection_hostname }}/{{ matrix_postgres_db_name }}?user={{ matrix_postgres_connection_username }}&password={{ matrix_postgres_connection_password }}'
```
email notifications are not sent any more.

**Comment by maxidorius** [comment]
> email notifications are not sent any more.

Could you clarify what is actually happening? Are logs being produced in mxisd? is the email sending fail?

**Comment by NullIsNot0** [comment]
Email notifications about invites were sent ok with version 1.3.1-1-gc636500, but when I upgraded to 1.4.2, notifications stopped working. Changing `mxisd.yaml` configuration according to documentation also did not help.
About logs: Invite events are displayed in Synapse logs, but nothing is displayed in Mxisd. No logs are generated by mxisd during invite event.

**Comment by NullIsNot0** [comment]
One more interesting thing: when I reverted back to version 1.3.1-1-gc636500, I received all the missing e-mails about invites when I was using 1.4.2.

**Comment by NullIsNot0** [comment]
OK, I had to change `{{ matrix_synapse_as_token }}` with `{{ matrix_synapse_hs_token }}` and vice versa, so the config becomes:
```yaml
endpoint:
    toHS:
        ...
        token: '{{ matrix_synapse_as_token }}'
    toAS:
        ...
        token: '{{ matrix_synapse_hs_token }}'
```
Seems that config parameters `toHS` (need to provide synapse's AS) and `toAS` (need to provide synapse's HS) are with meaning that we need to provide key to communicate with other side. Names confused me, and I specified incorrect keys.
Closing the issue.
