### ISSUE TITLE
Missing documentation on session policy validation

### ISSUE THREAD

**Issue by abeluck** [kamax-matrix/mxisd#180]
The following is in the config:

```
# Disable outbound federation and isolate the identity server from the rest of the Matrix network
# source: https://github.com/kamax-matrix/mxisd/blob/master/docs/features/federation.md
lookup:
  recursive:
    enabled: false
invite:
  resolution:
    recursive: false
session:
  policy:
    validation:
      forLocal:
        toRemote:
          enabled: false
      forRemote:
        toRemote:
          enabled: false

```

Yet the linked documentation does not have information regarding the `session.policy` settings.

I see some docs regarding session policies [here](https://github.com/kamax-matrix/mxisd/blob/3bebb33147552f26466578fad01e3348adb8cc1b/docs/threepids/session/session.md#federation), yet it doesn't cover the `[to|for][Local|Remote]` settings. 

As someone interested in running both private, sem-open, and open servers with mxisd as the identity server, it would be very helpful to have these options clarified.
