### ISSUE TITLE
New Identity store: executable

### ISSUE THREAD

**Issue by maxidor** [kamax-matrix/mxisd#58]
Create a new Identity store which is backed by executable commands on the system.
The data will be provided either as env or arguments, whichever is set.

Configuration example:
```
exec:
  auth:
    command: "/path/to/exec"
    env:
      - "USER=$user"
      - "PASS=$pass
    args: [ "--auth", "-u", "$user", "-p", "$pass" ]
    return_code: 
      success: [ 0, 128 ]
```

To figure out: what output format(s) should we accept

Relates to: #36
